In [1]:
data.raw <- read.csv("all.csv")
summary(data.raw)

       X                 State
 Min.   :  1.0   UP         : 70
 1st Qu.:148.2   MP         : 45
 Median :295.5   Bihar      : 37
 Mean   :295.5   Maharashtra: 35
 3rd Qu.:442.8   Rajasthan  : 32
 Max.   :590.0   TN         : 30
                 (Other)    :341
                                        District      Persons
 District North                             :  2   Min.   :  31394
 District Adilabad (01), Andhra Pradesh (28):  1   1st Qu.: 812718
 District Agra (15), Uttar Pradesh (09)     :  1   Median :1487712
 District Ahmadabad (07), Gujarat (24)      :  1   Mean   :1732902
 District Ahmadnagar (26), Maharashtra (27) :  1   3rd Qu.:2395986
 District Aizawl (03), Mizoram (15)         :  1   Max.   :9610788
 (Other)                                    :583
     Males            Females        Growth..1991...2001.     Rural
 Min.   :  15893   Min.   :  14783   17.59  :  3          -      :  9
 1st Qu.: 420751   1st Qu.: 389044   18.84  :  3          1000912:  1
 Median : 770616   Median : 713332   19.32  :  3          1002742:  1
 Mean   : 896660   Mean   : 836242   22.72  :  3          1004071:  1
 3rd Qu.:1248934   3rd Qu.:1142946   11.98  :  2          1005539:  1
 Max.   :4916370   Max.   :4694418   13     :  2          1010931:  1
                                     (Other):574          (Other):576
     Urban     Scheduled.Caste.population Percentage...SC.to.total
 -      :  9   -      : 13                -      : 13
 10107  :  1   5      :  2                0.01   :  2
 10653  :  1   10409  :  1                0.02   :  2
 108310 :  1   12     :  1                0.03   :  2
 116198 :  1   13276  :  1                0      :  1
 (Other): 55   (Other):  9                (Other):  8
 NA's   :522   NA's   :563                NA's   :562
 Number.of.households Household.size..per.household.
 Min.   :   6054      Min.   :4.000
 1st Qu.: 155930      1st Qu.:5.000
 Median : 268609      Median :5.000
 Mean   : 325823      Mean   :5.436
 3rd Qu.: 433702      3rd Qu.:6.000
 Max.   :1838426      Max.   :8.000
 NA's   :3            NA's   :3
 Sex.ratio..females.per.1000.males. Sex.ratio..0.6.years.
 Min.   : 591.0                     Min.   : 766.0
 1st Qu.: 895.0                     1st Qu.: 912.0
 Median : 938.0                     Median : 942.0
 Mean   : 934.8                     Mean   : 929.4
 3rd Qu.: 974.5                     3rd Qu.: 962.0
 Max.   :1147.0                     Max.   :1035.0
 NA's   :3                          NA's   :3
 Scheduled.Tribe.population Percentage.to.total.population..ST.
 -      : 50                -      : 50
 1      :  1                0.01   : 28
 100088 :  1                0.02   : 15
 10029  :  1                0      : 11
 100416 :  1                0.04   :  7
 (Other):533                (Other):476
 NA's   :  3                NA's   :  3
 Persons..literate Males..Literate   Females..Literate Persons..literacy.rate
 Min.   :  13424   Min.   :   8733   Min.   :   4177   Min.   :30.17
 1st Qu.: 414420   1st Qu.: 254140   1st Qu.: 150045   1st Qu.:55.71
 Median : 769305   Median : 468180   Median : 289660   Median :64.59
 Mean   : 944285   Mean   : 567073   Mean   : 377212   Mean   :64.00
 3rd Qu.:1220172   3rd Qu.: 761788   3rd Qu.: 472653   3rd Qu.:73.64
 Max.   :6617264   Max.   :3853376   Max.   :2763888   Max.   :96.51

 Males..Literatacy.Rate Females..Literacy.Rate Total.Educated
 Min.   :39.75          Min.   :18.58          Min.   :  13424
 1st Qu.:67.84          1st Qu.:41.54          1st Qu.: 408772
 Median :75.89          Median :52.40          Median : 767630
 Mean   :74.63          Mean   :52.60          Mean   : 944478
 3rd Qu.:82.97          3rd Qu.:63.38          3rd Qu.:1230916
 Max.   :97.64          Max.   :96.26          Max.   :6617264
                                               NA's   :3
 Data.without.level Below.Primary        Primary            Middle
 Min.   :   105     Min.   :   3821   Min.   :   3146   Min.   :   2481
 1st Qu.:  9301     1st Qu.: 106577   1st Qu.: 106862   1st Qu.:  64744
 Median : 20222     Median : 206569   Median : 199177   Median : 116314
 Mean   : 33894     Mean   : 243767   Mean   : 246428   Mean   : 152429
 3rd Qu.: 42265     3rd Qu.: 321885   3rd Qu.: 323873   3rd Qu.: 193492
 Max.   :877837     Max.   :2465907   Max.   :1586123   Max.   :1133954
 NA's   :3          NA's   :3         NA's   :3         NA's   :3
 Matric.Higher.Secondary.Diploma Graduate.and.Above  X0...4.years
 Min.   :   2497                 Min.   :   415     Min.   :  2547
 1st Qu.:  70974                 1st Qu.: 17629     1st Qu.: 82788
 Median : 151446                 Median : 37862     Median :161891
 Mean   : 204171                 Mean   : 63622     Mean   :186595
 3rd Qu.: 258431                 3rd Qu.: 71045     3rd Qu.:255782
 Max.   :2041567                 Max.   :868911     Max.   :918006
 NA's   :3                       NA's   :3          NA's   :3
 X5...14.years     X15...59.years    X60.years.and.above..Incl..A.N.S..
 Min.   :   5764   Min.   :  18019   Min.   :  2178
 1st Qu.: 194530   1st Qu.: 466260   1st Qu.: 60021
 Median : 371009   Median : 807175   Median :109091
 Mean   : 427263   Mean   : 986586   Mean   :133762
 3rd Qu.: 578904   3rd Qu.:1364307   3rd Qu.:182240
 Max.   :2333062   Max.   :5758483   Max.   :743405
 NA's   :3         NA's   :3         NA's   :3
 Total.workers      Main.workers     Marginal.workers   Non.workers
 Min.   :   9308   Min.   :   8420   Min.   :    611   Min.   :  12136
 1st Qu.: 337505   1st Qu.: 247782   1st Qu.:  77954   1st Qu.: 470094
 Median : 580664   Median : 435437   Median : 134736   Median : 891914
 Mean   : 677575   Mean   : 527189   Mean   : 150386   Mean   :1055328
 3rd Qu.: 906921   3rd Qu.: 692218   3rd Qu.: 208630   3rd Qu.:1430184
 Max.   :3751057   Max.   :2971039   Max.   :1220945   Max.   :5946126

             SC.1.Name   SC.1.Population            SC.2.Name
 1.Chamar etc.    :175   Min.   :      2   2.Chamar etc. : 57
 1.Mahar etc.     : 40   1st Qu.:  46086   2.Bhambi etc. : 29
 1.Madiga         : 18   Median : 106706   2.Dusadh etc. : 21
 1.Mahyavansi etc.: 18   Mean   : 152126   2.Mang etc.   : 21
 1.Namasudra      : 17   3rd Qu.: 198947   2.Balmiki etc.: 16
 (Other)          :271   Max.   :1396353   (Other)       :382
 NA's             : 51   NA's   :13        NA's          : 64
 SC.2.Population                  SC.3.Name   SC.3.Population
 Min.   :     1   3.Chamar etc.        : 38   Min.   :     1
 1st Qu.: 15497   3.Dhobi              : 38   1st Qu.:  6731
 Median : 39661   3.Bhangi etc.        : 26   Median : 18037
 Mean   : 57614   3.Bhambi etc.        : 25   Mean   : 26567
 3rd Qu.: 72527   3.Generic Castes etc.: 24   3rd Qu.: 36454
 Max.   :437085   (Other)              :373   Max.   :239230
 NA's   :13       NA's                 : 66   NA's   :13
     Religeon.1.Name Religeon.1.Population     Religeon.2.Name
 1.Buddhists :  6    Min.   :  19477       2.Buddhists : 28
 1.Christians: 28    1st Qu.: 670972       2.Christians: 44
 1.Hindus    :470    Median :1234862       2.Hindus    : 57
 1.Muslims   : 14    Mean   :1430416       2.Muslims   :374
 1.Others    :  8    3rd Qu.:1903613       2.Others    : 17
 1.Sikhs     : 11    Max.   :8224779       2.Sikhs     : 17
 NA's        : 53                          NA's        : 53
 Religeon.2.Population     Religeon.3.Name Religeon.3.Population
 Min.   :    531       3.Christians:135    Min.   :    90
 1st Qu.:  42788       3.Muslims   :108    1st Qu.:  4508
 Median : 138001       3.Jains     : 90    Median : 13343
 Mean   : 248915       3.Sikhs     : 75    Mean   : 39601
 3rd Qu.: 316690       3.Buddhists : 55    3rd Qu.: 37858
 Max.   :2295967       (Other)     : 74    Max.   :488697
                       NA's        : 53
                            ST.1.Name   ST.1.Population
 No Scheduled Tribes in this area: 50   243    :  3
 1.Bhil etc.                     : 45   1      :  2
 1.Generic Tribes etc.           : 38   150    :  2
 1.Gond etc.                     : 36   160    :  2
 1.Tharu                         : 27   189    :  2
 1.Santal                        : 25   (Other):528
 (Other)                         :369   NA's   : 51
                 ST.2.Name   ST.2.Population                 ST.3.Name
 2.Generic Tribes etc.: 42   85     :  5     3.Generic Tribes etc.: 64
 2.Gond etc.          : 27   22     :  4     3.Bhotia             : 19
 2.Bhil etc.          : 22   6      :  4     3.Gond etc.          : 14
 2.Bhotia             : 21   68     :  3     3.Naikda etc.        : 14
 2.Tharu              : 17   1      :  2     3.Oraon              : 14
 (Other)              :411   (Other):519     (Other)              :415
 NA's                 : 50   NA's   : 53     NA's                 : 50
 ST.3.Population      Imp.Town.1.Name Imp.Town.1.Population
 1      :  7     (MB)         : 17    Min.   :    996
 10     :  5     No Urban Area:  9    1st Qu.:  52537
 16     :  4     (M)          :  8    Median : 100968
 3      :  4     1.DMC(U) Part:  7    Mean   : 248160
 9      :  4     (M Cl)       :  3    3rd Qu.: 213236
 (Other):514     (Other)      :525    Max.   :4572876
 NA's   : 52     NA's         : 21    NA's   :14
       Imp.Town.2.Name Imp.Town.2.Population       Imp.Town.3.Name
 (M)           :  6    Min.   :    482       (M)           :  7
 2.DMC(U) Part :  6    1st Qu.:  22701       3.DMC(U) Part :  6
 (M Cl)        :  3    Median :  40514       (M Cl)        :  3
 2.DMC (U) Part:  2    Mean   :  68727       (NP)          :  2
 (MB)          :  1    3rd Qu.:  68720       3.DMC (U) Part:  2
 (Other)       :475    Max.   :2433835       (Other)       :428
 NA's          : 97    NA's   :64            NA's          :142
 Imp.Town.3.Population Total.Inhabited.Villages Drinking.water.facilities
 Min.   :   605        Min.   :    2.0          Min.   :    2.0
 1st Qu.: 17390        1st Qu.:  467.8          1st Qu.:  466.2
 Median : 29149        Median :  891.0          Median :  886.5
 Mean   : 41224        Mean   : 1016.5          Mean   : 1009.7
 3rd Qu.: 47965        3rd Qu.: 1386.0          3rd Qu.: 1376.5
 Max.   :704002        Max.   :10548.0          Max.   :10475.0
 NA's   :108           NA's   :12               NA's   :12
 Safe.Drinking.water Electricity..Power.Supply. Electricity..domestic.
 Min.   :    1.0     Min.   :   2.0             -      : 81
 1st Qu.:  442.8     1st Qu.: 311.5             1      :  6
 Median :  881.5     Median : 645.5             3      :  5
 Mean   :  992.0     Mean   : 774.8             101    :  4
 3rd Qu.: 1368.8     3rd Qu.:1086.8             120    :  4
 Max.   :10455.0     Max.   :4835.0             (Other):478
 NA's   :12          NA's   :12                 NA's   : 12
 Electricity..Agriculture. Primary.school   Middle.schools
 -      :138               Min.   :   1.0   -      : 26
 1      : 19               1st Qu.: 397.5   207    :  5
 2      : 13               Median : 758.5   243    :  5
 11     : 10               Mean   : 796.8   417    :  5
 14     : 10               3rd Qu.:1133.8   127    :  4
 (Other):192               Max.   :6133.0   (Other):533
 NA's   :208               NA's   :12       NA's   : 12
 Secondary.Sr.Secondary.schools    College    Medical.facility
 105    :  6                    -      : 90   118    :  4
 42     :  6                    1      : 67   197    :  4
 68     :  6                    2      : 50   229    :  4
 102    :  5                    3      : 37   279    :  4
 104    :  5                    4      : 34   375    :  4
 (Other):550                    (Other):260   (Other):558
 NA's   : 12                    NA's   : 52   NA's   : 12
 Primary.Health.Centre Primary.Health.Sub.Centre
 16     : 15           28     : 10
 18     : 15           52     :  8
 20     : 15           -      :  7
 14     : 14           11     :  7
 25     : 14           20     :  7
 (Other):505           (Other):539
 NA's   : 12           NA's   : 12
 Post..telegraph.and.telephone.facility  Bus.services Paved.approach.road
 Min.   :   2.0                         146    :  6   197    :  5
 1st Qu.: 172.5                         103    :  4   345    :  5
 Median : 354.5                         209    :  4   436    :  4
 Mean   : 419.7                         300    :  4   443    :  4
 3rd Qu.: 580.8                         47     :  4   163    :  3
 Max.   :2346.0                         (Other):556   (Other):557
 NA's   :12                             NA's   : 12   NA's   : 12
 Mud.approach.road Permanent.House Semi.permanent.House Temporary.House
 -      :  8       Min.   : 1.60   Min.   : 1.00        Min.   : 0.10
 138    :  4       1st Qu.:28.23   1st Qu.:14.60        1st Qu.: 3.40
 143    :  4       Median :47.55   Median :28.85        Median :10.75
 147    :  3       Mean   :47.62   Mean   :32.86        Mean   :19.49
 171    :  3       3rd Qu.:66.30   3rd Qu.:47.17        3rd Qu.:30.18
 (Other):556       Max.   :98.60   Max.   :95.00        Max.   :85.60
 NA's   : 12